spring.application.name=eln-backend

server.port=8081
# Connexion PostgreSQL (adaptez selon votre environnement local / docker-compose)
#spring.datasource.url=jdbc:postgresql://localhost:5432/eln_db
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/eln_db
spring.datasource.username=eln_user
spring.datasource.password=test123

# En dev : Hibernate crée/adapte les tables automatiquement à partir des entités.
# En production, remplacer par "validate" et gérer les migrations avec Flyway/Liquibase.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:changez-moi-en-production-avec-une-cle-longue-et-aleatoire-d-au-moins-32-caracteres}
jwt.expiration-ms=86400000